# Site settings
name: Mahdi Raza Khunt
title: Mahdi Raza Khunt | Data Science
description: 
url: https://mrkhunt.github.io/
baseurl: ''
email: mrkhunt@uwaterloo.ca
cover: https://mrkhunt.github.io/img/og.png
logo: https://mrkhunt.github.io/img/emojis/technologist.png
resume: https://mrkhunt.github.io/resume.pdf
social:
  - title: email
    url: mailto:mrkhunt@uwaterloo.ca
  - title: twitter
    url: https://twitter.com/mathymahdi
  - title: instagram
    url: https://instagram.com/mathymahdi
  - title: github
    url: https://github.com/mrkhunt
  - title: linkedin
    url: https://www.linkedin.com/in/mrkhunt

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
